In [1]:
import numpy as np
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
arr.shape

(6,)

In [9]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [13]:
arr[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.empty(2)

array([0., 0.])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,9,2)# IT apply steps

array([1, 3, 5, 7])

In [ ]:
print(np.arange(9,1,-1))# Reverse order

[9 8 7 6 5 4 3 2]


In [24]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#Adding, removing, and sorting elements

In [39]:
arr=np.arange(10)
np.sort(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.concatenate((a,b)))
print(a*b)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6 14 24 36 50]


In [ ]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [52]:
np.concatenate((x,y),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [61]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [60]:
arr.ndim

2

In [62]:
arr.size

8

In [63]:
arr.shape

(2, 4)

#Can you reshape an array?

In [66]:
a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [70]:
np.reshape(a,newshape=(1,12))

C:\Users\a864911\AppData\Local\Temp\ipykernel_26460\4048762238.py:1: DeprecationWarning: `newshape` keyword argument is deprecated, use `shape=...` or pass shape positionally instead. (deprecated in NumPy 2.1)
  np.reshape(a,newshape=(1,12))


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

How to convert a 1D array into a 2D array (how to add a
new axis to an array)

Indexing and slicing

In [3]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [6]:
data[-2:]

array([2, 3])

In [11]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[a<=5]


array([1, 2, 3, 4, 5])

In [13]:
dt=a<=5
a[dt]

array([1, 2, 3, 4, 5])

In [15]:
a[a % 2==0]

array([ 2,  4,  6,  8, 10, 12])

In [20]:
print(a)
np.nonzero(a>5)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

How to create an array from existing data

In [21]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [2]:
x=np.arange(1,25)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [8]:
np.split(x,4)#Split array into size

[array([1, 2, 3, 4, 5, 6]),
 array([ 7,  8,  9, 10, 11, 12]),
 array([13, 14, 15, 16, 17, 18]),
 array([19, 20, 21, 22, 23, 24])]

In [21]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b1=a[0,:]
b1[0]=99
b1

array([99,  2,  3,  4])

In [24]:
b2=a.copy()
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Basic array operations

In [29]:
a=np.ones(2,dtype=int)
b=a.copy()
b

array([1, 1])

In [32]:
a.sum()

np.int64(2)

In [33]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [35]:
b.sum(axis=0)

array([3, 3])

Creating matrices

In [38]:
data=np.array([[1,2],[3,4],[5,6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [40]:
data[0,1]
data[0:2,0]

array([1, 3])

In [43]:
data.max()
data.min()
data.mean()

np.float64(3.5)

In [44]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [49]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [50]:
np.max(data,axis=1)

array([2, 5, 6])

In [51]:
np.max(data,axis=0)

array([5, 6])

In [3]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
print(data)
print(ones)
                    

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


In [4]:
data+ones

array([[2, 3],
       [4, 5]])

In [5]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
print(data)
print(ones_row)


[[1 2]
 [3 4]
 [5 6]]
[[1 1]]


In [ ]:
data*ones_row
data+ones_row

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
np.random.rand(3,5,2)

array([[[0.46198598, 0.78800531],
        [0.87163914, 0.78179409],
        [0.49274854, 0.24952667],
        [0.33766635, 0.96679943],
        [0.39722573, 0.10617127]],

       [[0.63673886, 0.44415958],
        [0.17262136, 0.01628388],
        [0.07793521, 0.76845373],
        [0.24707242, 0.26985785],
        [0.24381817, 0.90123077]],

       [[0.20049959, 0.71343343],
        [0.406133  , 0.40526601],
        [0.41484735, 0.81641372],
        [0.91640702, 0.27642392],
        [0.56310379, 0.70240541]]])

In [24]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
np.unique(a,return_index=True)
np.unique(a,return_counts=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1]))

In [25]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [29]:
np.unique(a_2d,axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Transposing and reshaping a matrix

In [31]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
data.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [35]:
data.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [36]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

How to reverse an array

In [37]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [44]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
np.flip(arr_2d,axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [51]:
np.flip(arr_2d,axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [54]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
np.flip(arr_2d[:,1],axis=0)


array([10,  6,  2])

Reshaping and flattening multidimensional arrays

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [60]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a1=x.flatten() # it create new array and changes not reflect to original array
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
a1[0]=99
a1

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a2=x.ravel()# It update on original array
a2[0]=99
x

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
help(max)

Welcome to Python 3.13's help utility! If this is your first time using
Python, you should definitely check out the tutorial at
https://docs.python.org/3.13/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To get a list of available
modules, keywords, symbols, or topics, enter "modules", "keywords",
"symbols", or "topics".

Each module also comes with a one-line summary of what it does; to list
the modules whose name or summary contain a given string such as "spam",
enter "modules spam".

To quit this help utility and return to the interpreter,
enter "q", "quit" or "exit".



In [1]:
max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more positional arguments, return the largest argument.
Type:      builtin_function_or_method

In [6]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a?

Type:        ndarray
String form: [1 2 3 4 5 6]
Length:      6
File:        c:\users\a864911\appdata\local\programs\python\python313\lib\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : dat

In [8]:
def double(a):
    '''This function is used to double input value'''
    return a*a

In [11]:
double?

Signature: double(a)
Docstring: This function is used to double input value
File:      c:\users\a864911\appdata\local\temp\ipykernel_10072\3022953568.py
Type:      function

How to save and load NumPy objects

In [3]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a


array([1, 2, 3, 4, 5, 6])

In [4]:
np.save('filename_numpy',a)

In [5]:
np.load('filename_numpy.npy')

array([1, 2, 3, 4, 5, 6])