In [56]:
#Numpy Notes

In [1]:
import numpy as np

In [58]:
arr=np.array([1,2,3,4,5])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [61]:
np.arange(1,4)

array([1, 2, 3])

In [62]:
np.linspace(1,5,3)

array([1., 3., 5.])

In [63]:
arr=np.array([1,2,3,4])
arr.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [64]:
mulDim=np.array([[1,2,3,4],[5,6,7,8]])
mulDim

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
print(mulDim.flatten()) # convert mult-dimenshional array into single array
flatarr=mulDim.flatten()

[1 2 3 4 5 6 7 8]


In [66]:
flatarr[1:]

array([2, 3, 4, 5, 6, 7, 8])

In [67]:
print(len(flatarr))
flatarr[-2:]

8


array([7, 8])

In [68]:
arr=np.array([10,20,30,40,50,60])
arr

array([10, 20, 30, 40, 50, 60])

In [69]:
arr.size

6

In [70]:
arr.dtype

dtype('int64')

In [71]:
arr_1=np.array([1.0,'test',3,4,5,6,7,8,9,10])
arr_1 

array(['1.0', 'test', '3', '4', '5', '6', '7', '8', '9', '10'],
      dtype='<U32')

In [72]:
type(arr_1)

numpy.ndarray

In [73]:
arr_1.ndim

1

In [74]:
arr_1.itemsize

128

In [75]:
arr_2=np.array([1])
arr_2.itemsize

8

In [76]:
arr_1.nbytes

1280

In [77]:
MultArr=np.array([[10,20,30],[40,50,60]])
MultArr.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [78]:
MultArr.max()

np.int64(60)

In [79]:
MultArr.sum() #addition of total number's

np.int64(210)

In [84]:
np.arange(24).reshape(12,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [ ]:
arr1=np.array([10,20,30,0,0,13])
arr1.nonzero() # return index

(array([0, 1, 2, 5]),)

In [87]:
np.count_nonzero(arr1)

4

In [88]:
np.sort(arr1)

array([ 0,  0, 10, 13, 20, 30])

In [3]:
nums=np.array([10,20,30])

In [6]:
print(nums+5)
print(nums*5)
print(nums/5)


[15 25 35]
[ 50 100 150]
[2. 4. 6.]


In [7]:
np.diginal()

AttributeError: module 'numpy' has no attribute 'diginal'

In [11]:
# Create a 3x3 matrix
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [12]:
np.diagonal(a)

array([1, 5, 9])

In [13]:
np.trace(a)

np.int64(15)

In [17]:
a=np.array([[10,20,30],[1,2,3]])
b=np.array([[40,50,60],[1,2,3]])
print(a+b)


[[50 70 90]
 [ 2  4  6]]


In [22]:
10 in a

True

In [ ]:
arr1=np.array([[1,2,3],[3,4,6]]) 
arr2=np.array([[4,5,6],[41,51,61]]) 
arr=np.concatenate((arr1,arr2),axis=0)  # Vertically
print(arr)

[[ 1  2  3]
 [ 3  4  6]
 [ 4  5  6]
 [41 51 61]]


In [29]:
arr1=np.array([[1,2,3],[3,4,6]]) 
arr2=np.array([[4,5,6],[41,51,61]]) 
arr=np.concatenate((arr1,arr2),axis=0) # Horonzintal
print(arr)

[[ 1  2  3]
 [ 3  4  6]
 [ 4  5  6]
 [41 51 61]]


In [35]:
a=np.array([10,20,30])
b=np.array([100,200,300])
np.vstack((a,b)) #vstack- vertical

array([[ 10,  20,  30],
       [100, 200, 300]])

In [36]:
a=np.array([10,20,30])
b=np.array([100,200,300])
np.hstack((a,b)) #vstack- vertical

array([ 10,  20,  30, 100, 200, 300])

In [7]:
num1=np.array([10,20,30,40])
num2=np.array([1,2,3])

In [ ]:
print(num1*num2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [14]:
print(np.mean(num1))
print(np.var(num1))
print(np.std(num1))

25.0
125.0
11.180339887498949


In [23]:
num_new=np.arange(5)
num_new
print(num_new>100)

[False False False False False]


In [31]:
num1=np.arange(10)
num2=num1.copy()
print(num2)
num1[0]=100
print(num2)
print(num1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]


In [35]:
num3=num1.view()
print(num3)
num1[0]=99
print(f"Num1 {num1}")
print(f"Num3 {num3}")

[100   1   2   3   4   5   6   7   8   9]
Num1 [99  1  2  3  4  5  6  7  8  9]
Num3 [99  1  2  3  4  5  6  7  8  9]


In [37]:
print(id(num1))
print(id(num2))

2238674889552
2238674891280


In [ ]:
newarr=np.array([[10,20,30,40],[1,2,3,4]])
# print(np.resize(newarr,2))
print(np.resize(newarr,(100,100)))

[[10 20 30 ... 20 30 40]
 [ 1  2  3 ...  2  3  4]
 [10 20 30 ... 20 30 40]
 ...
 [ 1  2  3 ...  2  3  4]
 [10 20 30 ... 20 30 40]
 [ 1  2  3 ...  2  3  4]]


In [58]:
newarr=np.array([[10,20,5],[1,2,5]])
print(np.reshape(newarr,(3,2)))

[[10 20]
 [ 5  1]
 [ 2  5]]


In [59]:
num1=np.array([[1,2],[3,4]])

In [61]:
print(np.sum(num1,axis=0))

[4 6]


In [62]:
print(np.sum(num1,axis=1))

[3 7]


In [78]:
np.random.randint(1,10,(3,2))

array([[2, 9],
       [3, 6],
       [9, 1]], dtype=int32)

In [83]:
countarr=np.array([1,2,3,4,4,5,6,6,7,7,7,7,8])
print(np.bincount(countarr))
print(np.unique_counts(countarr))

[0 1 1 1 2 1 2 4 1]
UniqueCountsResult(values=array([1, 2, 3, 4, 5, 6, 7, 8]), counts=array([1, 1, 1, 2, 1, 2, 4, 1]))


In [86]:
np.eye(1)

array([[1.]])

In [ ]:
import pandas as pd
data={'A':[1,2,3,4],'B':[5,6,7,8]}
df=pd.DataFrame(data)


In [91]:
swapAxis=np.array([[1,2],[3,4],[5,6],[7,8]])
print(swapAxis.T)

[[1 3 5 7]
 [2 4 6 8]]


In [95]:
print(np.swapaxes(swapAxis,1,0))
print(np.swapaxes(swapAxis,0,1))

[[1 3 5 7]
 [2 4 6 8]]
[[1 3 5 7]
 [2 4 6 8]]


In [101]:
arr=[1,2,3,4,5,6]
print([x*2 for x in arr if x>=2])
print([x*2 for x in arr ])

[4, 6, 8, 10, 12]
[2, 4, 6, 8, 10, 12]
