In [3]:
import numpy as np
np.__version__

'2.2.6'

In [13]:
np.random.randint(2,30,(10,10))

array([[15, 26, 26,  7, 23, 11,  6,  6,  4,  3],
       [19,  8, 13, 22,  7, 25, 14, 27, 20,  7],
       [21, 12,  7,  9,  3,  3,  6, 19, 21, 10],
       [18, 11, 23, 21, 10,  7,  3, 28, 27, 21],
       [ 7,  8, 28, 28, 19, 21,  2, 16,  5, 16],
       [ 6, 11,  2, 11, 20, 29,  2, 18,  8, 17],
       [28, 24, 11, 22, 22, 11,  8, 12, 13, 21],
       [ 9, 17, 12,  6, 17,  8, 13, 20, 12, 20],
       [28, 26, 22, 24, 26,  5, 24,  7, 18, 10],
       [ 9, 11, 26, 11,  4, 12,  2,  6, 22, 16]], dtype=int32)

In [19]:
np.random.randint(1,12,(10,10))

array([[11,  1,  5,  8,  9,  2,  1,  4,  8,  2],
       [ 4,  4, 11,  2,  3,  7,  5, 11, 11,  4],
       [ 5, 10,  2,  2, 11,  4, 10,  1,  4,  4],
       [ 2,  3,  5,  6,  3,  8, 10, 11,  7,  5],
       [ 7,  5,  6,  1,  7,  2,  3,  5,  6, 10],
       [ 2,  1, 10,  6,  4, 11, 10,  7,  6,  2],
       [ 9,  4,  7,  9,  3,  4, 11,  9,  2,  6],
       [ 2, 11,  4, 11,  8,  9, 10,  5, 10,  4],
       [ 1, 11,  6,  5,  8,  8,  6,  6,  1,  8],
       [ 4,  2,  6,  5, 10,  5,  6,  2,  5,  5]], dtype=int32)

In [34]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [44]:
b=np.random.randint(1,13,(6,2))
b
type(b)

numpy.ndarray

In [45]:
b[:]

array([[ 3,  8],
       [ 5,  8],
       [10,  9],
       [ 8,  9],
       [11,  1],
       [ 9,  1]], dtype=int32)

Slicing

In [47]:
b[:]

array([[ 3,  8],
       [ 5,  8],
       [10,  9],
       [ 8,  9],
       [11,  1],
       [ 9,  1]], dtype=int32)

In [49]:
b[1:4]

array([[ 5,  8],
       [10,  9],
       [ 8,  9]], dtype=int32)

In [53]:
arr=np.random.randint(0,100,(10,10))
arr

array([[35, 53, 41, 32, 23, 76, 68, 24, 61, 96],
       [78, 68,  6, 56, 87, 69, 58,  4, 34, 52],
       [18, 73, 70, 71,  8, 33, 11, 40, 17, 53],
       [80, 86, 64, 77, 78, 85, 66, 27,  1, 18],
       [83, 99,  6, 93, 31,  9, 19, 55, 11,  2],
       [12, 19, 16, 98, 93, 95, 86,  5, 58, 48],
       [32, 37, 99, 92, 41, 85, 75, 16, 30,  1],
       [79, 51, 29, 11, 23, 67, 25, 14,  2, 22],
       [58, 80,  5,  2, 19, 39, 16, 47, 26,  4],
       [73,  7, 48,  1,  6, 64, 73, 40, 85, 42]], dtype=int32)

In [ ]:
arr[::-1]# Print reverse of an array

array([[73,  7, 48,  1,  6, 64, 73, 40, 85, 42],
       [58, 80,  5,  2, 19, 39, 16, 47, 26,  4],
       [79, 51, 29, 11, 23, 67, 25, 14,  2, 22],
       [32, 37, 99, 92, 41, 85, 75, 16, 30,  1],
       [12, 19, 16, 98, 93, 95, 86,  5, 58, 48],
       [83, 99,  6, 93, 31,  9, 19, 55, 11,  2],
       [80, 86, 64, 77, 78, 85, 66, 27,  1, 18],
       [18, 73, 70, 71,  8, 33, 11, 40, 17, 53],
       [78, 68,  6, 56, 87, 69, 58,  4, 34, 52],
       [35, 53, 41, 32, 23, 76, 68, 24, 61, 96]], dtype=int32)

In [55]:
arr[::-2]# Print reverse of an array

array([[73,  7, 48,  1,  6, 64, 73, 40, 85, 42],
       [79, 51, 29, 11, 23, 67, 25, 14,  2, 22],
       [12, 19, 16, 98, 93, 95, 86,  5, 58, 48],
       [80, 86, 64, 77, 78, 85, 66, 27,  1, 18],
       [78, 68,  6, 56, 87, 69, 58,  4, 34, 52]], dtype=int32)

In [56]:
arr[::-3]# Print reverse of an array

array([[73,  7, 48,  1,  6, 64, 73, 40, 85, 42],
       [32, 37, 99, 92, 41, 85, 75, 16, 30,  1],
       [80, 86, 64, 77, 78, 85, 66, 27,  1, 18],
       [35, 53, 41, 32, 23, 76, 68, 24, 61, 96]], dtype=int32)

In [57]:
arr[0:10:3]

array([[35, 53, 41, 32, 23, 76, 68, 24, 61, 96],
       [80, 86, 64, 77, 78, 85, 66, 27,  1, 18],
       [32, 37, 99, 92, 41, 85, 75, 16, 30,  1],
       [73,  7, 48,  1,  6, 64, 73, 40, 85, 42]], dtype=int32)

In [58]:
arr.max()

np.int32(99)

In [59]:
arr.min()

np.int32(1)

In [60]:
from numpy import *
median(arr)

np.float64(41.0)

In [63]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [65]:
row=4
col=5

In [66]:
col

5

In [69]:
print(mat[4,5])

45


In [70]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [71]:
col=6

In [74]:
mat[:,7]

array([ 7, 17, 27, 37, 47, 57, 67, 77, 87, 97])

In [75]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [76]:
id(mat)

2969506608016

In [77]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [81]:
mat[mat<5]

array([0, 1, 2, 3, 4])