In [2]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --------- ------------------------------ 3.1/12.6 MB 25.9 MB/s eta 0:00:01
   -------------- ------------------------- 4.5/12.6 MB 13.1 MB/s eta 0:00:01
   ---------------- ----------------------- 5.2/12.6 MB 10.7 MB/s eta 0:00:01
   -------------------- ------------------- 6.6/12.6 MB 8.2 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.6 MB 7.3 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 6.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 6.5 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 6.2 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 6.0 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 5.7 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [ ]:
np.__version__

'2.2.6'

In [5]:
import sys
print(sys.version)

3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]


In [1]:
my_list=[0,1,2,3,4,5]
print(my_list)

[0, 1, 2, 3, 4, 5]


In [2]:
type(my_list)

list

In [8]:
arr=np.array(my_list)
type(arr)

numpy.ndarray

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(10)#Create array 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [24]:
np.arange(0,5,2) 

array([0, 2, 4])

In [26]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [27]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [28]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,10),dtype=int)#2X10

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])